### ISSUE TITLE
Error occurred trying to load cordova.js

### ISSUE THREAD

**Issue by blefebvre** [phonegap/phonegap-template-react-hot-loader#1]
To reproduce:
- follow the README to generate a new project, install dependencies, and use npm to launch the iOS Simulator
- connect Safari web inspector to the simulator
- hit 'refresh' in the web inspector window to view app initialization errors

Result:
- the request for cordova.js returns a 404:

![screen shot 2016-04-16 at 2 16 15 pm](https://cloud.githubusercontent.com/assets/1048207/14582876/ea6df196-03de-11e6-8f34-649057fbc0f4.png)

**Comment by devgeeks** [comment]
Yeah, that's kinda to be expected. The hot loader server is really more about the HTML/CSS/JS, it doesn't know what platform cordova.js to serve. That would be a great addition if I could work it out.

At the moment, the hot reloading part of the plugin is more useful for iterating on the UI and the logic of the components.

I'll ask around the team and see if they have an idea how we could do it. Maybe at the very least it could serve the browser platform version of cordova.js

**Comment by devgeeks** [comment]
Another awesome feature would be to build in something like `phonegap serve` that could use some kind of black magic to serve the hot reloading server to the PhoneGap Developer App.

**Comment by blefebvre** [comment]
Thanks for the quick response @devgeeks! I'll move over to the PG Dev app when I need to work on plugin-dependant functionality.

**Comment by devgeeks** [comment]
Best you can hope for with `phonegap serve` for now is

```
npm run prepare -- browser && phonegap serve
```

I am looking into it though...
